// app/layout.js
import { Rubik } from "next/font/google";
import "./globals.css";
import ClientProvider from "@/components/ClientProvider";

const font = Rubik({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ClientProvider>{children}</ClientProvider>
      </body>
    </html>
  );
}
